# Generated by Django 5.0.6 on 2024-09-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_dress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='image',
        ),
        migrations.CreateModel(
            name='DressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dresses/')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.dress')),
            ],
        ),
    ]
