# Generated by Django 5.0.6 on 2024-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddinginfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
