# Generated by Django 5.0.6 on 2024-10-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_weddinginfo_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddinginfo',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
